%YAML:1.0


# Waypoint matrix
parameterMatrix: !!opencv-matrix
  rows: 6   # kpx kvx kpa kpw para
  cols: 3   # x y z
  dt: d
  data:
    [
        -1.1, -1.1 ,0.8,
        -1.0, -1.0, 0.6,
        0,0,0,
        0.85, 0.85, 0.8,
        -0.155, 0.155, 0.5,
#        70, 0, 0
        69.812 , 0 , 0
    ]


targetMatrix: !!opencv-matrix
  rows: 3   #p v a
  cols: 3   # x y z
  dt: d
  data:
    [
       0,0,2,
       0,0,0,
       0,0,0
    ]
